// JavaScript Document
L.marker([	-33.4890418	,	-70.7557861	])	.bindPopup("	<b>Lugar</b><br>	J.V Nueva esperanza II	<br><b>Dirección</b><br>	181 Pasaje Achupallas, Maipú, Santiago	<br><b>Barrio</b><br>	La Farfana	<br><b>Estado</b><br>	Implementada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.4987395	,	-70.7675495	])	.bindPopup("	<b>Lugar</b><br>	Villa Blanco Encalada	<br><b>Dirección</b><br>	889 Avenida Argentina, Maipú, Santiago	<br><b>Barrio</b><br>	Hospital-Campo de batalla	<br><b>Estado</b><br>	Implementada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.505311	,	-70.7768585	])	.bindPopup("	<b>Lugar</b><br>	J.V General Baquedano 1	<br><b>Dirección</b><br>	Galicia & Goliat, Maipú, Santiago	<br><b>Barrio</b><br>	Hospital-Campo de batalla	<br><b>Estado</b><br>	Implementada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.5158732	,	-70.7431477	])	.bindPopup("	<b>Lugar</b><br>	Población Pizarreño	<br><b>Dirección</b><br>	5106 El Estanque, Maipú, Santiago	<br><b>Barrio</b><br>	Esquina blanca- Cuatro alamos	<br><b>Estado</b><br>	Implementada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.5209425	,	-70.758902	])	.bindPopup("	<b>Lugar</b><br>	Villa Pajaritos sur	<br><b>Dirección</b><br>	168-A Block Sur interior, Maipú, Santiago	<br><b>Barrio</b><br>	Pajaritos sur	<br><b>Estado</b><br>	Implementada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.4785707	,	-70.7518224	])	.bindPopup("	<b>Lugar</b><br>	J.V Versalles II y IV	<br><b>Dirección</b><br>	4706 Las meninas, Maipú, Santiago	<br><b>Barrio</b><br>	Longitudinal	<br><b>Estado</b><br>	Proyectada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.5023179	,	-70.7381047	])	.bindPopup("	<b>Lugar</b><br>	Volcan Tacora	<br><b>Dirección</b><br>	1563 Sewell, Maipú, Santiago	<br><b>Barrio</b><br>	Clotario Blest	<br><b>Estado</b><br>	Proyectada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.5088137	,	-70.744665	])	.bindPopup("	<b>Lugar</b><br>	Villa CIC El alto	<br><b>Dirección</b><br>	127 El Alto, Maipú, Santiago	<br><b>Barrio</b><br>	Riesco central	<br><b>Estado</b><br>	Proyectada	"	).openPopup().addTo(	EcoSed);
L.marker([	-33.5254542	,	-70.794514	])	.bindPopup("	<b>Lugar</b><br>	J.V Pehuen 4 y 5	<br><b>Dirección</b><br>	270 La Galaxia, Maipú, Santiago	<br><b>Barrio</b><br>	Pehuen	<br><b>Estado</b><br>	Proyectada	"	).openPopup().addTo(	EcoSed);

