// JavaScript Document
L.marker([	-33.5058	,	-70.7741212	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTO ORGANICO	<br><b>Lugar</b><br>	CESFAM Ahues c/15 días	<br><b>Dirección</b><br>	2200 Av. Independencia	<br><b>Encargado</b><br>	Sergio Toledo	<br><b>Fecha inicio</b><br>	19-jun.	<br><b>Horario</b><br>	Lunes 15:30 - 17:00	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5034783	,	-70.7769762	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTO ORGANICO	<br><b>Lugar</b><br>	Jardín Infantil Madre Selva	<br><b>Dirección</b><br>	2701 Galicia	<br><b>Encargado</b><br>	Gianfranco Lagos	<br><b>Fecha inicio</b><br>	20-jun.	<br><b>Horario</b><br>	Martes 09:30-12:30	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5108204	,	-70.7660961	])	.bindPopup("	<b>Nombre actividad</b><br>	Construcción sustentable (reparación invernadero)	<br><b>Lugar</b><br>	Jardín Infantil Campanita	<br><b>Dirección</b><br>	1750 El Carmen	<br><b>Encargado</b><br>	Erik Guajardo	<br><b>Fecha inicio</b><br>	13-jun.	<br><b>Horario</b><br>	Martes 10:00- 13:00h	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5458187	,	-70.7814338	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTOS ORGÁNICOS	<br><b>Lugar</b><br>	Jardin Infantil Esdras C/15 DÍAS Seguimiento	<br><b>Dirección</b><br>	60 Esdras	<br><b>Encargado</b><br>	Sergio Toledo	<br><b>Fecha inicio</b><br>	13-jun.	<br><b>Horario</b><br>	Martes 15:30- 17:00	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5063035	,	-70.7875284	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTO ORGANICO	<br><b>Lugar</b><br>	J.V. Los Araucanos	<br><b>Dirección</b><br>	2435 Colo colo	<br><b>Encargado</b><br>	Oscar Alvear - Francisca Valdés	<br><b>Fecha inicio</b><br>	27-jun.	<br><b>Horario</b><br>	Martes 15:30 - 17:15	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5063035	,	-70.7875284	])	.bindPopup("	<b>Nombre actividad</b><br>	CONSTRUCCION SUSTENTABLE	<br><b>Lugar</b><br>	J.V. Los Araucanos	<br><b>Dirección</b><br>	2435 Colo colo	<br><b>Encargado</b><br>	Matias Chavez	<br><b>Fecha inicio</b><br>	27-jun.	<br><b>Horario</b><br>	Martes 15:30 - 17:15	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5140409	,	-70.75322	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTOS ORGÁNICOS	<br><b>Lugar</b><br>	Junta de Vecinos Ricardo Ayala	<br><b>Dirección</b><br>	398 Ricardo Ayala	<br><b>Encargado</b><br>	Oscar Alvear	<br><b>Fecha inicio</b><br>	21-jun.	<br><b>Horario</b><br>	Miércoles 10:00 - 12:00	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5283561	,	-70.7963843	])	.bindPopup("	<b>Nombre actividad</b><br>	FORJADORES AMBIENTALES	<br><b>Lugar</b><br>	Liceo Tecnológico E. Kirberg	<br><b>Dirección</b><br>	1561 Av. El Conquistador	<br><b>Encargado</b><br>	Erik Guajardo	<br><b>Fecha inicio</b><br>	07-jun.	<br><b>Horario</b><br>	Miércoles 15:30 - 16:30	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5171014	,	-70.7462005	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTOS ORGÁNICOS (1 vez al mes)	<br><b>Lugar</b><br>	LOS PIONEROS	<br><b>Dirección</b><br>	883 Los Pioneros	<br><b>Encargado</b><br>	Oscar Alvear	<br><b>Fecha inicio</b><br>	29-jun.	<br><b>Horario</b><br>	Jueves 16:30 - 17:30	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5144541	,	-70.7456708	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTOS ORGÁNICOS c/15 días	<br><b>Lugar</b><br>	Junta de Vecinos Pozo al Monte	<br><b>Dirección</b><br>	1303 Pozo al monte	<br><b>Encargado</b><br>	Oscar Alvear	<br><b>Fecha inicio</b><br>	22-jun.	<br><b>Horario</b><br>	Jueves 15:30 - 16:30	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edamjun);
L.marker([	-33.5175229	,	-70.7467011	])	.bindPopup("	<b>Nombre actividad</b><br>	seguimiento 1 vez al mes	<br><b>Lugar</b><br>	La Pastora	<br><b>Dirección</b><br>	Plaza La Pastora con Elizabeth Heisse	<br><b>Encargado</b><br>	Oscar Alvear	<br><b>Fecha inicio</b><br>	29-jun.	<br><b>Horario</b><br>	Jueves 15:30 - 16:30	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.510412	,	-70.7237796	])	.bindPopup("	<b>Nombre actividad</b><br>	CONSTRUCCIÓN INVERNADERO	<br><b>Lugar</b><br>	Liceo Maipú	<br><b>Dirección</b><br>	8720 Camino A Melipilla	<br><b>Encargado</b><br>	Erik Guajardo	<br><b>Fecha inicio</b><br>	08-jun.	<br><b>Horario</b><br>	Jueves 10:00-13:00	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edamjun);
L.marker([	-33.4668584	,	-70.7552906	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTOS ORGÁNICOS	<br><b>Lugar</b><br>	Eco sede los claveles de pajaritos	<br><b>Dirección</b><br>	5519 Ministro Antonio Varas	<br><b>Encargado</b><br>	Sergio Toledo	<br><b>Fecha inicio</b><br>	27-jun.	<br><b>Horario</b><br>	Martes 15:00 - 17:00	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
L.marker([	-33.473155	,	-70.756197	])	.bindPopup("	<b>Nombre actividad</b><br>	CONSTRUCCION SUSTENTABLE	<br><b>Lugar</b><br>	CESFAM Luis Ferrada	<br><b>Dirección</b><br>	5161 Tierra Fértil	<br><b>Encargado</b><br>	Erik Guajardo	<br><b>Fecha inicio</b><br>	29-jun.	<br><b>Horario</b><br>	Jueves 15:30- 17:00	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edamjun);
