// JavaScript Document
L.marker([	-33.5088007	,	-70.7553773	])	.bindPopup("	<b>Nombre actividad</b><br>	BIOPREPARADOS	<br><b>Lugar</b><br>	Biblioteca Municipal	<br><b>Dirección</b><br>	1921 Alberto Llona	<br><b>Encargado</b><br>	Cristian Osorio	<br><b>Fecha inicio</b><br>	07-Ago	<br><b>Horario</b><br>	Lunes 15:15 - 17:15	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.4890082	,	-70.7674109	])	.bindPopup("	<b>Nombre actividad</b><br>	BIOPREPARADOS	<br><b>Lugar</b><br>	Biblioteca Municipal Manuel Rojas	<br><b>Dirección</b><br>	1354 Victoria de Abril	<br><b>Encargado</b><br>	Cristian Osorio	<br><b>Fecha inicio</b><br>	09-Ago	<br><b>Horario</b><br>	Miércoles 15:15 - 17:15	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.5458187	,	-70.7814338	])	.bindPopup("	<b>Nombre actividad</b><br>	Biodiversidad	<br><b>Lugar</b><br>	Jardin Infantil Esdras	<br><b>Dirección</b><br>	60 Esdras	<br><b>Encargado</b><br>	Camila Romero	<br><b>Fecha inicio</b><br>	29-Ago	<br><b>Horario</b><br>	Martes 15:30- 17:00	<br><b>Estado</b><br>	PROGRAMADO	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.563447	,	-70.774155	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTO ORGANICO	<br><b>Lugar</b><br>	COPA LAUTARO	<br><b>Dirección</b><br>	18111 Calle Lautaro	<br><b>Encargado</b><br>	Sergio Toledo	<br><b>Fecha inicio</b><br>	03-Ago	<br><b>Horario</b><br>	Jueves 10:00 - 11:30	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.5137989	,	-70.7970094	])	.bindPopup("	<b>Nombre actividad</b><br>	REUTILIZACION	<br><b>Lugar</b><br>	CESFAM Ana Maria Yuricic	<br><b>Dirección</b><br>	1841 El Conquistador	<br><b>Encargado</b><br>	Susana Alarcón	<br><b>Fecha inicio</b><br>	03-Ago	<br><b>Horario</b><br>	Jueves 16:00 -18:00	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.505466	,	-70.7908796	])	.bindPopup("	<b>Nombre actividad</b><br>	REUTILIZACION	<br><b>Lugar</b><br>	J.V.Los Jardines de Rinconada. Centro de Madres Luz de la Esperanza	<br><b>Dirección</b><br>	2640 Avda. Rinconada	<br><b>Encargado</b><br>	Susana Alarcón	<br><b>Fecha inicio</b><br>	03-Ago	<br><b>Horario</b><br>	jueves 10:30 - 12:30	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.5247437	,	-70.7715697	])	.bindPopup("	<b>Nombre actividad</b><br>	REUTILIZACION	<br><b>Lugar</b><br>	Jardín Infantil San José	<br><b>Dirección</b><br>	1033 Av. Nueva San Martín	<br><b>Encargado</b><br>	Aida Oliva	<br><b>Fecha inicio</b><br>	16-Ago	<br><b>Horario</b><br>	miércoles 10:30 - 12:00	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.5217604	,	-70.777528	])	.bindPopup("	<b>Nombre actividad</b><br>	REUTILIZACION	<br><b>Lugar</b><br>	Club de Adulto Mayor Los Diamantes	<br><b>Dirección</b><br>	1404 Av. Sur	<br><b>Encargado</b><br>	Marcela Gómez	<br><b>Fecha inicio</b><br>	22-Ago	<br><b>Horario</b><br>	martes 15:30 - 16:45	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.5146353	,	-70.7918868	])	.bindPopup("	<b>Nombre actividad</b><br>	CONSTRUCCION SUSTENTABLE	<br><b>Lugar</b><br>	Plaza El Huaso (c/15 días)	<br><b>Dirección</b><br>	2515 El Huaso	<br><b>Encargado</b><br>	Erik Guajardo	<br><b>Fecha inicio</b><br>	21-Ago	<br><b>Horario</b><br>	lunes 15:30 - 17:00 hrs	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.5146353	,	-70.7918868	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTO URBANO	<br><b>Lugar</b><br>	Plaza El Huaso (c/15 días)	<br><b>Dirección</b><br>	2515 El Huaso	<br><b>Encargado</b><br>	Sergio Toledo	<br><b>Fecha inicio</b><br>	07-Ago	<br><b>Horario</b><br>	lunes 15:30 - 17:00 hrs	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.4826216	,	-70.7451677	])	.bindPopup("	<b>Nombre actividad</b><br>	CONSTRUCCION SUSTENTABLE	<br><b>Lugar</b><br>	Teatro Municipal (funcionarios)	<br><b>Dirección</b><br>	Sala 1	<br><b>Encargado</b><br>	Karen Flores - Erik guajardo	<br><b>Fecha inicio</b><br>	03-Ago	<br><b>Horario</b><br>	jueves 10:30 - 12:30	<br><b>Estado</b><br>	COMPLETADO	"	).openPopup().addTo(	edAmAgo);
L.marker([	-33.5115857	,	-70.7976848	])	.bindPopup("	<b>Nombre actividad</b><br>	HUERTO ORGANICO	<br><b>Lugar</b><br>	Escuela de Párvulos San Juan Leonardi	<br><b>Dirección</b><br>	3421 Senadora María de La Cruz	<br><b>Encargado</b><br>	Sergio Toledo	<br><b>Fecha inicio</b><br>	06-Ago	<br><b>Horario</b><br>	Martes 10:00 a 12:00	<br><b>Estado</b><br>	VIGENTE	"	).openPopup().addTo(	edAmAgo);
