// JavaScript Document
L.marker([	-33.4909463	,	-70.78008	])	.bindPopup("	<b>Lugar</b><br>	Alicante del Rosal	<br><b>Dirección</b><br>	920 Ingeniero Eduardo Dominguez, Maipú, Santiago	<br><b>Barrio</b><br>	La Farfana	<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
L.marker([	-33.4998533	,	-70.7760228	])	.bindPopup("	<b>Lugar</b><br>	Tomas Vargas y Arcaya	<br><b>Dirección</b><br>	1440 Asunción, Maipú, Santiago	<br><b>Barrio</b><br>	Hospital-Campos de batalla	<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
L.marker([	-33.50073	,	-70.7571908	])	.bindPopup("	<b>Lugar</b><br>	Universidad del mar	<br><b>Dirección</b><br>	2897 Pajaritos, Maipú, Santiago	<br><b>Barrio</b><br>	Maipu centro	<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
L.marker([	-33.5093298	,	-70.7470388	])	.bindPopup("	<b>Lugar</b><br>	CTP CODEDUC	<br><b>Dirección</b><br>	1900 Segunda transversal, Maipú, Santiago	<br><b>Barrio</b><br>	Maipu centro	<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
L.marker([	-33.5171382	,	-70.7505759	])	.bindPopup("	<b>Lugar</b><br>	Vicente Reyes Palazuelos	<br><b>Dirección</b><br>	500 Elizabeth Heisse, Maipú, Santiago	<br><b>Barrio</b><br>		<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
L.marker([	-33.5161352	,	-70.7691138	])	.bindPopup("	<b>Lugar</b><br>	Andalue	<br><b>Dirección</b><br>	860 San Jose, Maipú, Santiago	<br><b>Barrio</b><br>	Templo votivo	<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
L.marker([	-33.5253918	,	-70.7574392	])	.bindPopup("	<b>Lugar</b><br>	Sofia Infante Hurtado	<br><b>Dirección</b><br>	80 Nueva San Martin, Maipú, Santiago	<br><b>Barrio</b><br>	Pajaritos sur	<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
L.marker([	-33.5194125	,	-70.7934177	])	.bindPopup("	<b>Lugar</b><br>	Liceo Nacional de Maipú	<br><b>Dirección</b><br>	2471 Portales, Maipú, Santiago	<br><b>Barrio</b><br>	Sol poniente	<br><b>Estado</b><br>	Activo	"	).openPopup().addTo(	EEdPtoVer);
